+++
title = "Remove"
description = "More about sshRemove step."
tags = ["steps", "remove", "file", "directory"]
weight = 5
date = "2018-06-27"
lastmodifierdisplayname = "Naresh Rayapati"
+++

=== sshRemove

Remove a file or directory on the remote host.

==== Usage

[width="60%",cols="^2,4,6",options="header"]
|===
|Key
|Type
|Description

|*remote*
|Remote, *Mandatory*, Refer to the Remote config for more details.
|Host config to run the command on.

|*path*
|String, *Mandatory*
|file or directory path on the remote node

|*failOnError*
|boolean, default: `true`.
|If this is `false`, no job failure would occur though there is an error while running the command.

|*dryRun*
|boolean, default: `false`
|If this is true, no actual connection or operation is performed.
|===

{{% notice note %}}
More about remote key can be found in configuration section.
{{% /notice %}}

==== Example

```groovy
node {
  def remote = [:]
  remote.name = 'test'
  remote.host = 'test.domain.com'
  remote.user = 'root'
  remote.password = 'password'
  remote.allowAnyHosts = true
  stage('Remote SSH') {
    sshRemove remote: remote, path: "abc.sh"
  }
}
```

{{% notice tip %}}
Please take note to surround the code with a node.
{{% /notice %}}

