+++
title = "Script"
description = "More about sshScript step."
tags = ["steps", "script"]
weight = 2
date = "2018-06-27"
lastmodifierdisplayname = "Naresh Rayapati"
+++

=== sshScript

This step executes given script(file) on remote node and responds with output.

==== Usage

[width="60%",cols="^2,4,6",options="header"]
|===
|Key
|Type
|Description

|*remote*
|Remote, *Mandatory*, Refer to the Remote config for more details.
|Host config to run the command on.

|*script*
|String, *Mandatory*
|Script file name from the workspace, current this doesn't support script with arguments. For that option you would need to copy over the file to remote node and run it as a command.

|*failOnError*
|boolean, default: `true`.
|If this is `false`, no job failure would occur though there is an error while running the command.

|*dryRun*
|boolean, default: `false`
|If this is true, no actual connection or operation is performed.
|===

{{% notice note %}}
More about remote key can be found in configuration section.
{{% /notice %}}

==== Example

```groovy
node {
  def remote = [:]
  remote.name = 'test'
  remote.host = 'test.domain.com'
  remote.user = 'root'
  remote.password = 'password'
  remote.allowAnyHosts = true
  stage('Remote SSH') {
    writeFile file: 'abc.sh', text: 'ls -lrt'
    sshScript remote: remote, script: "abc.sh"
  }
}
```

{{% notice tip %}}
Please take note to surround the code with a node.
{{% /notice %}}

